spring:
  application:
    name: cadastro-autores-api
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/livraria}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        lorimedeiros: trace
    org:
      springframework:
        web: debug
        security: trace

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  override-with-generic-response: false


# production
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false


# homologacao / teste
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: false
